# Generated by Django 5.2 on 2025-04-23 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=240)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_seller_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('updated_add', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
