# Generated by Django 5.2 on 2025-04-23 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='created_add',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='updated_add',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='unique_seller_id',
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
