# Generated by Django 5.2 on 2025-04-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_branch_product_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='company_name',
            new_name='store_name',
        ),
    ]
