# Generated by Django 5.2 on 2025-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_branch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchuser',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
