# Generated by Django 5.2 on 2025-04-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
