# Generated by Django 5.2 on 2025-04-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-04-28 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(default='2024-04-28 00:00:00', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(default='2024-04-28 00:00:00', max_length=20),
            preserve_default=False,
        ),
    ]
