# Generated by Django 5.2 on 2025-04-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_buyer_created_at_buyer_full_name_buyer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchuser',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='buyer',
            name='role',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
