# Generated by Django 5.2 on 2025-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_address_order_payment_method_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CARD', 'Credit/Debit Card'), ('NETBANKING', 'Net Banking')], max_length=50),
        ),
    ]
