# Generated by Django 5.2 on 2025-04-14 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCatagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Niwar', 'Niwar'), ('Cow', 'Cow'), ('AG', 'Agriculture Tools'), ('HT', 'Hardware Tools')])),
            ],
        ),
    ]
