# Generated by Django 5.2 on 2025-04-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatagories',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='productcatagories',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
