# Generated by Django 5.2 on 2025-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0003_productcatagories_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcatagories',
            name='features',
        ),
        migrations.AlterField(
            model_name='productcatagories',
            name='type',
            field=models.CharField(choices=[('Niwar', 'Niwar'), ('Cow', 'Cow'), ('AG', 'Agriculture Tools'), ('HT', 'Hardware Tools')]),
        ),
    ]
