# Generated by Django 5.2 on 2025-04-15 10:39

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0004_remove_productcatagories_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='All_Products/')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Niwar', 'Niwar'), ('Cow', 'Cow Care'), ('Dog', 'Dog Care'), ('Horse', 'Horse Care'), ('AG', 'Agriculture Tools'), ('HT', 'Hardware Tools'), ('Rope', 'Ropes'), ('PM', 'Packing Items'), ('Hatha', 'Hatha'), ('Home', 'House Holds')], max_length=20)),
                ('description', tinymce.models.HTMLField(default='')),
                ('stock_status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
            ],
        ),
    ]
