# Generated by Django 5.2 on 2025-04-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0005_fullshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullshop',
            options={'verbose_name_plural': 'FullShop'},
        ),
    ]
