# Generated by Django 5.2 on 2025-04-17 09:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0007_itemreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCatagories',
        ),
        migrations.AddField(
            model_name='fullshop',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
