# Generated by Django 5.2 on 2025-04-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0008_delete_productcatagories_fullshop_new_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemReview',
        ),
    ]
