# Generated by Django 5.2 on 2025-04-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0009_delete_itemreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullShop',
        ),
    ]
