# Generated by Django 5.2 on 2025-04-17 10:21

import autoslug.fields
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product_image', '0010_delete_fullshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Niwar', 'Niwar'), ('Cow', 'Cow Care'), ('Dog', 'Dog Care'), ('Horse', 'Horse Care'), ('AG', 'Agriculture Tools'), ('HT', 'Hardware Tools'), ('Rope', 'Ropes'), ('PM', 'Packing Items'), ('Hatha', 'Hatha'), ('Home', 'House Holds')], max_length=20)),
                ('description', tinymce.models.HTMLField(default='')),
                ('stock_status', models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=20)),
                ('new_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
            ],
            options={
                'verbose_name_plural': 'FullShop',
            },
        ),
    ]
