# Generated by Django 5.2 on 2025-04-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullshop',
            name='image',
            field=models.ImageField(default='default description', upload_to=''),
            preserve_default=False,
        ),
    ]
