# Generated by Django 5.2 on 2025-04-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0012_fullshop_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullshop',
            old_name='new_slug',
            new_name='slug',
        ),
    ]
