# Generated by Django 5.2 on 2025-04-18 10:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullshop',
            name='brief',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
