# Generated by Django 5.2 on 2025-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0015_fullshop_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullshop',
            name='brief',
            field=models.CharField(max_length=500),
        ),
    ]
