# Generated by Django 5.2 on 2025-04-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_image', '0018_fullshop_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullshop',
            name='price',
        ),
    ]
